import type { Metadata } from 'next';
import { Sora } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import Topbar from '@/components/shared/topbar';

const sora = Sora({
	variable: '--font-sora',
	subsets: ['latin'],
});


export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<ThemeProvider>
				<body
					className={`${sora.className} antialiased`}
				>
					<Topbar />
					{children}
				</body>
			</ThemeProvider>
		</html>
	);
}
